/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentDto } from '../../models/content-dto';

export interface GetAllContents$Params {
}

export function getAllContents(http: HttpClient, rootUrl: string, params?: GetAllContents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContentDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllContents.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ContentDto>>;
    })
  );
}

getAllContents.PATH = '/api/contents';
