/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropositionDto } from '../../models/proposition-dto';

export interface CreateProposition$Params {
  title: string;
  userId: number;
      body?: {
'file': Blob;
}
}

export function createProposition(http: HttpClient, rootUrl: string, params: CreateProposition$Params, context?: HttpContext): Observable<StrictHttpResponse<PropositionDto>> {
  const rb = new RequestBuilder(rootUrl, createProposition.PATH, 'post');
  if (params) {
    rb.query('title', params.title, {});
    rb.query('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropositionDto>;
    })
  );
}

createProposition.PATH = '/api/propositions';
