/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropositionDto } from '../../models/proposition-dto';

export interface GetAllPropositions$Params {
}

export function getAllPropositions(http: HttpClient, rootUrl: string, params?: GetAllPropositions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PropositionDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllPropositions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PropositionDto>>;
    })
  );
}

getAllPropositions.PATH = '/api/propositions';
