/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentDto {
  contentId?: number;
  id?: number;
  text?: string;
  userId?: number;
}
