/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentDto } from '../models/comment-dto';
import { QuestionDto } from '../models/question-dto';

export interface ContentDto {
  body?: string;
  category?: 'LAW' | 'ANNOUNCEMENT' | 'SURVEY';
  comments?: Array<CommentDto>;
  createdDate?: string;
  id?: number;
  questions?: Array<QuestionDto>;
  title?: string;
}
