/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuestionDto {
  contentId?: number;
  id?: number;
  questionText?: string;
  responseIds?: Array<number>;
  responseType?: 'SINGLE_CHOICE' | 'MULTIPLE_CHOICE' | 'YES_NO' | 'FREE_TEXT';
}
