/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResponseDto {
  answerText?: string;
  id?: number;
  questionId?: number;
  userId?: number;
}
