/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createResponse } from '../fn/response-controller/create-response';
import { CreateResponse$Params } from '../fn/response-controller/create-response';
import { deleteResponse } from '../fn/response-controller/delete-response';
import { DeleteResponse$Params } from '../fn/response-controller/delete-response';
import { getAllResponses } from '../fn/response-controller/get-all-responses';
import { GetAllResponses$Params } from '../fn/response-controller/get-all-responses';
import { getResponseById } from '../fn/response-controller/get-response-by-id';
import { GetResponseById$Params } from '../fn/response-controller/get-response-by-id';
import { ResponseDto } from '../models/response-dto';
import { updateResponse } from '../fn/response-controller/update-response';
import { UpdateResponse$Params } from '../fn/response-controller/update-response';

@Injectable({ providedIn: 'root' })
export class ResponseControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getResponseById()` */
  static readonly GetResponseByIdPath = '/api/responses/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getResponseById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getResponseById$Response(params: GetResponseById$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseDto>> {
    return getResponseById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getResponseById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getResponseById(params: GetResponseById$Params, context?: HttpContext): Observable<ResponseDto> {
    return this.getResponseById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ResponseDto>): ResponseDto => r.body)
    );
  }

  /** Path part for operation `updateResponse()` */
  static readonly UpdateResponsePath = '/api/responses/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateResponse()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateResponse$Response(params: UpdateResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseDto>> {
    return updateResponse(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateResponse$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateResponse(params: UpdateResponse$Params, context?: HttpContext): Observable<ResponseDto> {
    return this.updateResponse$Response(params, context).pipe(
      map((r: StrictHttpResponse<ResponseDto>): ResponseDto => r.body)
    );
  }

  /** Path part for operation `deleteResponse()` */
  static readonly DeleteResponsePath = '/api/responses/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteResponse()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteResponse$Response(params: DeleteResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteResponse(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteResponse$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteResponse(params: DeleteResponse$Params, context?: HttpContext): Observable<void> {
    return this.deleteResponse$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllResponses()` */
  static readonly GetAllResponsesPath = '/api/responses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllResponses()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllResponses$Response(params?: GetAllResponses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ResponseDto>>> {
    return getAllResponses(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllResponses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllResponses(params?: GetAllResponses$Params, context?: HttpContext): Observable<Array<ResponseDto>> {
    return this.getAllResponses$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ResponseDto>>): Array<ResponseDto> => r.body)
    );
  }

  /** Path part for operation `createResponse()` */
  static readonly CreateResponsePath = '/api/responses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createResponse()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createResponse$Response(params: CreateResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseDto>> {
    return createResponse(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createResponse$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createResponse(params: CreateResponse$Params, context?: HttpContext): Observable<ResponseDto> {
    return this.createResponse$Response(params, context).pipe(
      map((r: StrictHttpResponse<ResponseDto>): ResponseDto => r.body)
    );
  }

}
